dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  dbCreate: update
  username: root
  password: Abhi
  url: "jdbc:mysql://localhost:3306/grails_contactsbook?useSSL=false&serverTimezone=UTC"


environments:
  development:
    dataSource:
      dbCreate: update
      url: "jdbc:mysql://localhost:3306/grails_contactsbook?useSSL=false&serverTimezone=UTC"
#      url: "jdbc:mysql://localhost/ocb?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"